In [4]:
import numpy as np

In [5]:
#Project of Numpy

In [6]:
marks = np.array(([40,50,40,50,40],
                [60,40,80,90,70],
                [100,70,80,90,60]))

In [8]:
total_marks = np.sum(marks,axis = 1)

In [15]:
Higest_marks = np.max(total_marks)

In [17]:
Lowest_marks = np.min(total_marks)

In [19]:
Percentage =(total_marks / 500 )* 100

In [23]:
Class_Topper = np.max(Percentage)

In [25]:
Topper_sub = np.max(marks, axis = 0)

In [26]:
# Resulting the detials

In [42]:
print("Marks of Students is :\n",marks),
print(" \nTotal Marks of Student is : ",total_marks),
print("Highest Marks of Students : ",Higest_marks),
print("Lowest Marks of Student : ",Lowest_marks),
print("Makrs of Topper is : ",Class_Topper),
print("The Percentages of Students is : ",Percentage),
print("Topper subject marks  : ",Topper_sub)

Marks of Students is :
 [[ 40  50  40  50  40]
 [ 60  40  80  90  70]
 [100  70  80  90  60]]
 
Total Marks of Student is :  [220 340 400]
Highest Marks of Students :  400
Lowest Marks of Student :  220
Makrs of Topper is :  80.0
The Percentages of Students is :  [44. 68. 80.]
Topper subject marks  :  [100  70  80  90  70]
